import facebookIcon from "@/styles/ICONS/CRM/MiniCards/facebook.png";

//Modelo de implementação de dados do card do CRM;
export const initialData = {
  tasks: {
    "task-1": {
      id: "task-1",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "facebook",
      currentStatus: "started",
      event: "viewcontent",
    },
    "task-2": {
      id: "task-2",
      nome: "João",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "green",
      origin: "google",
      source: "google",
      currentStatus: "stopped",
      event: "search",
    },
    "task-3": {
      id: "task-3",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "facebook",
      currentStatus: "init",
      event: "initiate",
    },
    "task-4": {
      id: "task-4",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "instagram",
      currentStatus: "init",
      event: "viewcontent",
    },
    "task-5": {
      id: "task-5",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "facebook",
      currentStatus: "started",
      event: "initiate",
    },
    "task-6": {
      id: "task-6",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "google",
      source: "google",
      currentStatus: "started",
      event: "search",
    },
    "task-7": {
      id: "task-7",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "instagram",
      currentStatus: "stopped",
      event: "initiate",
    },
    "task-8": {
      id: "task-8",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "facebook",
      currentStatus: "init",
      event: "viewcontent",
    },
    "task-9": {
      id: "task-9",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "instagram",
      currentStatus: "stopped",
      event: "search",
    },
    "task-10": {
      id: "task-10",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "google",
      source: "google",
      currentStatus: "started",
      event: "search",
    },
    "task-11": {
      id: "task-11",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "google",
      source: "google",
      currentStatus: "started",
      event: "initiate",
    },
    "task-12": {
      id: "task-12",
      nome: "Pedro",
      data: "22/01/2025, 11:25:05",
      telefone: "(00) 0 0000-0000",
      app: "",
      lead: "red",
      origin: "meta",
      source: "instagram",
      currentStatus: "init",
      event: "viewcontent",
    },
  },
  columns: {
    "column-1": {
      id: "column-1",
      title: "Novos Leads",
      taskIds: ["task-1", "task-2", "task-3"],
    },
    "column-2": {
      id: "column-2",
      title: "Em Tratativa",
      taskIds: ["task-4"],
    },
    "column-3": {
      id: "column-3",
      title: "Leads Estagnados",
      taskIds: ["task-5"],
    },
    "column-4": {
      id: "column-4",
      title: "Agendados",
      taskIds: ["task-6"],
    },
    "column-5": {
      id: "column-5",
      title: "Compareceram",
      taskIds: ["task-7", "task-8", "task-9", "task-10", "task-11", "task-12"],
    },
    "column-6": {
      id: "column-6",
      title: "Não Compareceram",
      taskIds: [],
    },
  },
  // We use this to remember the order of the columns
  columnOrder: [
    "column-1",
    "column-2",
    "column-3",
    "column-4",
    "column-5",
    "column-6",
  ],
};
